### ISSUE TITLE
Literature review

### ISSUE THREAD

**Issue by juliohm** [vieira03/CellDeclusteringHeuristics#1]
It would be nice to review previous work on this subject, particularly studies that investigate different approaches to declustering.

**Comment by phacampos** [comment]
I have walkerlake 2d exaustive data set. There are several 3d block models in this link: https://mansci-web.uai.cl/minelib/Datasets.xhtml
[exaustivos.txt](https://github.com/vieira03/CellDeclusteringHeuristics/files/5856963/exaustivos.txt)

**Comment by juliohm** [comment]
Nice @phacampos ! Should this comment be placed in #2 instead?

**Comment by juliohm** [comment]
I opened this issue just curious about previous work. Are you aware of studies that investigate similar questions?

**Comment by phacampos** [comment]
Particularly about which method perform better, no. Issaks and Srivastava place this comment on their book (pag.243):
![image](https://user-images.githubusercontent.com/62719082/105514707-947baf80-5cb2-11eb-9e85-4d90b177f434.png)

**Comment by juliohm** [comment]
That is good news :) If @vieira03 can do a literature review to find possible overlaps with past work, we can find our potential contribution to this literature.

**Comment by vieira03** [comment]
Ok, I can do it.

**Comment by phacampos** [comment]
Also for reference: 
[1-s2.0-0098300489900435-main.pdf](https://github.com/vieira03/CellDeclusteringHeuristics/files/5857286/1-s2.0-0098300489900435-main.pdf)
