### ISSUE TITLE
Data sets

### ISSUE THREAD

**Issue by juliohm** [vieira03/CellDeclusteringHeuristics#2]
We need to select a data set or a few data sets with which we will perform the experiment. Ideally, we should have access to the final distribution of the mineral after the mine has been exhaustively drilled and blocks have been exhaustively extracted.

We could then play the experiment where we gradually reveal the drill holes and perform the declustering statistics over time to see how close they get to the final actual distribution.

**Comment by phacampos** [comment]
I have walkerlake 2d exaustive data set. There are several 3d block models in this link: https://mansci-web.uai.cl/minelib/Datasets.xhtml
[exaustivos.txt](https://github.com/vieira03/CellDeclusteringHeuristics/files/5856994/exaustivos.txt)
